Removed Order Requirements from test_pipeline_generation.py
datajoint/workflow-calcium-imaging pull request #101
Opened 2023-03-05 22:03 UTC by virenvarma007

Cleared issue #74 by making the code update. And cleared 2022-allen-institute-workshop.ipynb files keyboard interrupt error that made it to the final branch in the notebook to clean it up a bit.

2023-03-17 20:33 UTC, kabilar commented
@virenvarma007 Thanks for the discussion last week regarding this pull request.  I will provide specific suggestions in the next 1-2 weeks.

2023-03-20 10:20 UTC, virenvarma007 commented
Sure Sure Sir, No Problem

2023-03-26 01:28 UTC, kabilar commented on notebooks/2022-allen-institute-workshop.ipynb
We recently removed this notebook from the repository to simplify the tutorials.  Please pull from the upstream repository to fast forward your fork.

2023-03-26 01:31 UTC, kabilar commented on tests/test_pipeline_generation.py
> +    assert schema.Table.full_table_name in schema.OtherTable.parents()
Thanks @virenvarma007.  The code snippet provided in #74 was a template and will need to be adapted to the specific tables being tested.

2023-03-26 01:38 UTC, kabilar requested changes
@virenvarma007  Thanks for your contributions!  Once you make updates based on my suggestions above, please run the pytests to ensure that all pass.  Instructions for running the pytests can be found [here](https://datajoint.com/docs/elements/developer-guide/#pytests).  Please let me know if you have any questions.

2023-03-26 10:26 UTC, virenvarma007 commented on notebooks/2022-allen-institute-workshop.ipynb
Okay ok Sir, I'll pull from the upstream repo to fast forward the fork.

2023-03-26 10:27 UTC, virenvarma007 commented
Sure sure Sir, I'll run the tests and let you know the results soon.

2023-03-26 10:28 UTC, virenvarma007 commented
Sure sure Sir, I'll run the tests and let you know the results soon.

2023-03-26 10:55 UTC, closed without merging