DevContainer optimizations
datajoint/workflow-calcium-imaging pull request #111
Opened 2023-03-21 17:17 UTC by guzman-raphael

2023-03-21 18:18 UTC, kabilar requested changes
Thanks @guzman-raphael.  One comment above.  I am currently testing on my fork.

2023-03-21 18:37 UTC, kabilar commented
When I removed `pip install --no-cache-dir suite2p` from the Dockefile since we are installing suite2p from a forked version in the requirements.txt, there is a container error: `onCreateCommand failed with exit code 1`.

2023-03-22 03:46 UTC, guzman-raphael commented on .devcontainer/Dockerfile
> +    pip install --no-cache-dir suite2p && \
@kabilar I'd recommend us merging this for now and reviewing this again once we can discuss why Tolga's fork was needed and is so large. At least for the purposes of this demo, the included updates seem to work fine.

2023-03-22 03:48 UTC, guzman-raphael commented
In light of the upcoming demo at Bonn University I'll merge as-is since it seems functional.

2023-03-22 03:50 UTC, merged