Adding codebook env and cicd
datajoint/workflow-calcium-imaging pull request #63
Opened 2022-03-25 20:15 UTC by yambottle

2022-03-30 15:32 UTC, guzman-raphael requested changes
@yambottle Great work! :clap: 

Would you just double check on the cloning point?

2022-05-01 01:53 UTC, kabilar commented
Thank you, @yambottle!  I will defer to @guzman-raphael to review this work.

Prior to merging, let's decide on the discussion from [pull request #56](https://github.com/datajoint/workflow-array-ephys/pull/56#issuecomment-1114093572) in workflow-array-ephys.  Thanks!

2022-05-06 15:14 UTC, kabilar commented on docker/docker-compose-codebook_env.yaml
> +    image: registry.vathes.com/${REPO_OWNER}/codebook-${REPO_NAME}:jhub${JHUB_VER}-py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}
After discussion with @yambottle @guzman-raphael, we will publish to open-source DataJoint DockerHub.

2022-06-10 15:26 UTC, yambottle commented
> Hi @yambottle - Are there still things to address here? I'm interested in getting some of these pieces implemented across other element workflows. Lmk if I can support that process

It needs a little bit change since I updated the SciOps CICD, we need to follow the same template.

2022-06-27 14:53 UTC, kabilar commented
Hi @yambottle, since you are now working on centralizing the CI for the Workflows and Elements, would these updates still be applicable?  If not, we can close this pull request.  Thanks!

2022-09-13 20:06 UTC, closed without merging