Add docstrings for the docs API.
datajoint/workflow-calcium-imaging pull request #89
Opened 2022-11-03 22:43 UTC by tdincer

2022-11-03 22:47 UTC, CBroz1 commented on workflow_calcium_imaging/ingest.py
>      subject_csv_path="./user_data/subjects.csv", skip_duplicates=True, verbose=True
ideally, this PR would include typing suggestions for each argument
```suggestion
    subject_csv_path:str="./user_data/subjects.csv", skip_duplicates:bool=True, verbose:bool=True
```

2022-11-03 22:50 UTC, CBroz1 requested changes

2022-11-03 22:50 UTC, CBroz1 commented on workflow_calcium_imaging/ingest.py
> +    Ingest each level of experiment heirarchy for element-trial: recording, block (i.e.,
```suggestion
    Ingest session, block, trial, and event data.

    Ingest each level of experiment hierarchy for element-trial: recording, block (i.e.,
```

2022-11-03 22:50 UTC, CBroz1 commented on workflow_calcium_imaging/ingest.py
> +    """This is duplicated across wf-array-ephys and wf-calcium-imaging.
```suggestion
    """Ingest event alignment information
    
    This is duplicated across wf-array-ephys and wf-calcium-imaging.
```

2022-11-03 22:50 UTC, CBroz1 commented on workflow_calcium_imaging/paths.py
>  def get_imaging_root_data_dir():
Can this type suggest pathlib.Path?

```suggestion
def get_imaging_root_data_dir() -> SOMETHING:
```

2022-11-03 22:50 UTC, CBroz1 commented on workflow_calcium_imaging/paths.py
> +    """Retrieve the list of Prairieview files associated with a given Scan.
```suggestion
    """Retrieve the list of PrairieView files associated with a given Scan.
```

2022-11-09 15:21 UTC, tdincer commented on workflow_calcium_imaging/paths.py
>  def get_imaging_root_data_dir():
It returns either pathlib.Path or None.

2022-11-09 17:27 UTC, CBroz1 approved these changes
Looks good. Thanks @tdincer. Please confirm this is ready to merge

2022-12-02 16:03 UTC, CBroz1 approved these changes

2022-12-02 16:04 UTC, merged